### ISSUE TITLE
Feature request: running second order with auth cookie header ?

### ISSUE THREAD

**Issue by ehsandeep** [mhmdiaa/second-order#2]
in this way it may can explore more files, i mean `-js` files maybe ?

**Comment by mhmdiaa** [comment]
Good idea. It's on my ToDo list. I'll probably add it soon. Thanks!

**Comment by mhmdiaa** [comment]
Hi,

Just pushed the update. Now, you can use the `-cookie` flag to supply a list of comma-delimited cookies.

Thanks

**Comment by ehsandeep** [comment]
Great work @mhmdiaa, just curious if it supports Header as well? nowadays web applications use header based authentication as well.

**Comment by mhmdiaa** [comment]
Thanks. Right now, it doesn't, but it's on the backlog along with some other updates. BTW, if you know Go, pull requests are very welcome :)

**Comment by ehsandeep** [comment]
Sure, 1 more thing to notice @mhmdiaa, blacklist given endpoints to stop crawler to get logged out from application.

**Comment by ehsandeep** [comment]
Hey @mhmdiaa, is blacklist approach is for listed domain names only or it support the path as well eg: `domain.com/logout` ?

**Comment by mhmdiaa** [comment]
Hi @madaratech, yes `domain.com/logout` would work perfectly. The blacklist is basically a list of regular expressions that will be matched against the found URLs.

P.S: Pull the latest update. Due to a bug on the code, URLs were checked if they were found by a query, but not if they were scheduled to be crawled. I just fixed that.

**Comment by ehsandeep** [comment]
Thanks.
