### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by arbazkiraak** [mhmdiaa/second-order#4]
Hello @mhmdiaa  ,

Thanks for Creating this nice Tool ! , However i m facing problem while running it .

root@kali:~/go_projects/src/github.com/PuerkitoBio/goquery# go run second-order.go -base=https://site.com -depth=5 -output=output.json -js
second-order.go:16:2: found packages goquery (array.go) and main (second-order.go) in /root/go_projects/src/github.com/PuerkitoBio/goquery

**Comment by mhmdiaa** [comment]
Hi, thanks for giving it a try.
This error appears because you can't have more than one package per directory. In your current setup, you have second-order.go in the directory of goquery,
To solve this, just move second-order.go to another directory (that doesn't contain another package), and run it from there.
If you want to keep things organized (which I recommend), use `go get` to get the code instead.
```
go get github.com/mhmdiaa/second-order/
```
This will download the code to `$GOPATH/src/github.com/mhmdiaa/second-order/`, you can then run it with `go run` or compile it with `go build` or `go install`

**Comment by arbazkiraak** [comment]
Oops my bad , i was checking in /PuerkitoBio/goquery 

Sorry my bad . Thanks for the instruction :+1:
